- name: Set up auto-update cron job
  cron:
    name: "auto-update"
    user: root
    minute: "{{ auto_updates_minute }}"
    hour: "{{ auto_updates_hour }}"
    day: "{{ auto_updates_day }}"
    job: >
      logger 'Auto-update started' && apt update  2>&1 | logger -t auto-update && apt upgrade -y 2>&1 | logger -t auto-update && logger 'Auto-update finished'
      {% if auto_updates_reboot %}
      && [ -f /var/run/reboot-required ] && logger 'Reboot required, rebooting...' && reboot
      {% endif %}
  when: auto_updates_enabled

- name: Remove auto-update cron job if disabled
  cron:
    name: "auto-update"
    user: root
    state: absent
  when: not auto_updates_enabled

