---
- name: Remove cloud-init-generated Netplan config
  file:
    path: "/etc/netplan/50-cloud-init.yaml"
    state: absent
  when: netplan_remove_cloudinit_config

- name: Remove Netplan configs
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ netplan_remove_files }}"
  when: netplan_remove_files | length > 0

- name: Backup existing netplan configuration
  copy:
    src: "{{ netplan_config_file }}"
    dest: "{{ netplan_config_file }}.bak"
    remote_src: yes
  when: ansible_facts['os_family'] == "Debian"
  ignore_errors: yes  # in case file doesn’t exist

- name: Deploy netplan configuration
  copy:
    dest: "{{ netplan_config_file }}"
    content: "{{ netplan_config }}"
    owner: root
    group: root
    mode: '0644'
  notify: Apply netplan
