---
- name: Install RSnapshot
  apt:
    name: rsnapshot
    state: latest
    update_cache: yes

- name: Copy RSnapshot file to etc directory
  copy:
    src: "{{ rsnapshot_conf }}"
    dest: "/etc/rsnapshot.conf"
    mode: '0644'

- name: Create hourly job
  cron:
    name: "Hourly rsnapshot"
    minute: "0"
    job: "rsnapshot hourly 2>&1 | logger"
- name: Create daily job
  cron:
    name: "Daily rsnapshot"
    minute: "15"
    hour: "3"
    job: "rsnapshot daily 2>&1 | logger"
- name: Create weekly job
  cron:
    name: "Weekly rsnapshot"
    minute: "30"
    hour: "3"
    weekday: "1"
    job: "rsnapshot weekly 2>&1 | logger"
- name: Create monthly job
  cron:
    name: "Monthly rsnapshot"
    minute: "45"
    hour: "3"
    day: "1"
    job: "rsnapshot monthly 2>&1 | logger"
