---
- name: reload systemd
  become: true
  systemd:
    daemon_reload: true

- name: restart minecraft
  become: true
  systemd:
    name: minecraft
    state: restarted
  when: minecraft_auto_start
